FROM nginx:1.24-alpine

RUN addgroup -S user1 && \ 
    adduser -S -G user1 user1 && \
    rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/run/nginx /var/cache/nginx /var/log/nginx \
 && chown -R user1:user1 /var/run/nginx /var/cache/nginx /var/log/nginx \
 && chmod 755 /var/run/nginx /var/cache/nginx /var/log/nginx  /etc/nginx/conf.d 

USER user1

EXPOSE 8888

CMD ["nginx", "-g", "daemon off;"]
