FROM nginx:1.24-alpine

RUN addgroup -S user1 && \ 
    adduser -S -G user1 user1 && \
    rm /etc/nginx/conf.d/default.conf && \
    rm /etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY files /usr/share/nginx/files

RUN mkdir -p /var/run/nginx /var/cache/nginx /var/log/nginx \
 && chown -R user1:user1 /var/run/nginx /var/cache/nginx /var/log/nginx /usr/share/nginx/files \
 && chown -R root:root /etc/nginx/conf.d \
 && chmod 755 /var/run/nginx /var/cache/nginx /var/log/nginx /usr/share/nginx/files /etc/nginx/conf.d \
 && chmod 644 /etc/nginx/conf.d/* \
 && chmod -R 755 /usr/share/nginx/files

USER user1

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
